### ISSUE TITLE
missing CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ElijahAhianyo** [inforian/drf-pyotp#11]
Hi, is this project still being maintained? Realised there hasn't been any activity in 3 years! However, would be happy to add a contributing.md for starters if given the go ahead to create a PR :smile:

**Comment by inforian** [comment]
Hi,

You are most welcome to contribute to this project.

I didn't get any response from the community so didn't contribute that mush
after initial development.

**Comment by ElijahAhianyo** [comment]
sure. I created a PR #12 adding a file for just that. Feel free to close this issue after review

**Comment by inforian** [comment]
Thanks for the PR.

I'll surely review it. It may take some time since I am busy with
some other stuff currently.

**Comment by inforian** [comment]
@ElijahAhianyo Merged your PR.
